### ISSUE TITLE
请问如何可以实现皮肤搜索功能呢？

### ISSUE THREAD

**Issue by real-Shigure** [FiYHer/csgo_cheats#4]
皮肤列表找起来确实比较麻烦（之前为了找龙驹翻了半天列表hhhhh）听说皮肤名称被储存在了相关的std中，但我不太清楚应该如何做这样一个搜索功能（例如输入：awp即可在列表中选择出现的含有关键字的皮肤），请问可以写一个简单例子以供参考吗？谢谢！OTZ

**Comment by FiYHer** [comment]
兄弟,你是怎么获取武器皮肤和应用武器皮肤都不知道吧?不然怎么会这么简单的搜索功能都实现不了?
我的例子:https://github.com/FiYHer/csgo_cheats
别的例子:https://github.com/danielkrupinski/Osiris
我就简单说一下怎么获得武器皮肤数据和应用武器皮肤，看我发的txt文件吧，不懂再问吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"real-Shigure"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 凌晨1:52
收件人:&nbsp;"FiYHer/csgo_cheats"<csgo_cheats@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FiYHer/csgo_cheats] 请问如何可以实现皮肤搜索功能呢？ (#4)





 
皮肤列表找起来确实比较麻烦（之前为了找龙驹翻了半天列表hhhhh）听说皮肤名称被储存在了相关的std中，但我不太清楚应该如何做这样一个搜索功能（例如输入：awp即可在列表中选择出现的含有关键字的皮肤），请问可以写一个简单例子以供吗？谢谢！OTZ

**Comment by FiYHer** [comment]
如果你只需要一个武器搜索功能的话，我可以下次更新添加上去，但是你想知道怎么写的话，可以看我的第6次或者第7次提交的代码，那样子代码相对少一点，看懂代码的基本流程了要添加一个武器皮肤搜索后替换的功能是非常简单的事情

**Comment by real-Shigure** [comment]
Thx！多谢，我去看一下例子👌
