### ISSUE TITLE
大佬,请问 CSGO 播放的音频有何限制?

### ISSUE THREAD

**Issue by NMSAzulX** [FiYHer/csgo_cheats#6]
作者你好, 我在本地录制音频替换到游戏中,游戏出现 无效的采样率40000等字样, 请问您有这方面的经验吗?  我想写个工具替换音频.

**Comment by FiYHer** [comment]
> 作者你好, 我在本地录制音频替换到游戏中,游戏出现 无效的采样率40000等字样, 请问您有这方面的经验吗? 我想写个工具替换音频.
这个我不太懂呀

**Comment by NMSAzulX** [comment]
好的,  请问皮肤替换是什么原理,是更改内存中存储的模型吗?  我能否替换本地的文件, 让本地实现换肤的效果?  谢啦~

**Comment by FiYHer** [comment]
> 好的, 请问皮肤替换是什么原理,是更改内存中存储的模型吗? 我能否替换本地的文件, 让本地实现换肤的效果? 谢啦~

我没有尝试过本地替换文件，但我觉得替换文件比内存修改复杂的多，一般都是内存修改而已

**Comment by NMSAzulX** [comment]
感谢作者,  拥有一个花了呼哨的皮肤, 是我在CSGO游戏中一个梦想.  如果有单独替换皮肤的程序,就更好了.    坐等作者把功能这个程序解耦出来,,,,

**Comment by FiYHer** [comment]
> 感谢作者, 拥有一个花了呼哨的皮肤, 是我在CSGO游戏中一个梦想. 如果有单独替换皮肤的程序,就更好了. 坐等作者把功能这个程序解耦出来,,,,

https://github.com/FiYHer/external_csgo_skin
外部换肤

**Comment by NMSAzulX** [comment]
感谢大佬圆梦~ 我去试试, 这个有被封的风险吗?

**Comment by FiYHer** [comment]
> 感谢大佬圆梦~ 我去试试, 这个有被封的风险吗?

没经过处理，肯定的呀
